title: Ahmed Ashraf # your name (or website title) here
logo: "https://github.com/Ahmed-Ashraf-Khalil/ahmedashrafkhalil.github.io/assets/59618586/4e876db4-0834-4a45-8b6c-0336aeed5c88" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist Passionate about Data and all its applications.
  <br><br>
  <a href="https://www.linkedin.com/in/ahmed-ashraf-khalil">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/Ahmed-Ashraf-Khalil">View My Github Profile</a> 
  <br><br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
